---
- name: Converge
  hosts: all
  tasks:
    - name: "Include ansible-role-authorized-principals"
      include_role:
        name: "pmeyerra.authorized_principals"
      vars:
        authorized_principals:
          admin:
            - "barack"
            - "joe"
          service:
            - "carpool"
