---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: molecule-tests
    image: "geerlingguy/docker-ubuntu2204-ansible:latest"
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: testinfra
scenario:
  name: default
  test_sequence:
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - verify
    - destroy
